nodeone: node bot.js
nodetwo: node bot2.js
nodethree: node Mod.js
nodefour: node BC.js
nodefive: node tk.js
nodesix: node wl.js
nodeseven: node ga.js
nodeeight: node me.js
nodeeleven: node Zzetchen.js
cofeone: node cofesexy.js
cofetwo: node cofesexy2.js
cofethree: node cofesexy3.js
